# Generated by Django 4.2.11 on 2026-01-04 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ipam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(db_index=True, help_text='CIDR格式，例如: 192.168.10.0/24', max_length=43, unique=True, validators=[ipam.models.IPAddressValidator()], verbose_name='网络地址')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='网关地址')),
                ('netmask', models.GenericIPAddressField(blank=True, null=True, verbose_name='子网掩码')),
                ('vlan_id', models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)], verbose_name='VLAN ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '子网',
                'verbose_name_plural': '子网',
                'ordering': ['network'],
                'indexes': [models.Index(fields=['network'], name='ipam_subnet_network_737508_idx'), models.Index(fields=['vlan_id'], name='ipam_subnet_vlan_id_fbb65a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='设备名称')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP地址')),
                ('snmp_version', models.CharField(choices=[('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=10, verbose_name='SNMP版本')),
                ('snmp_community', models.CharField(blank=True, help_text='SNMPv2c使用', max_length=200, verbose_name='Community字符串')),
                ('snmp_username', models.CharField(blank=True, help_text='SNMPv3使用', max_length=200, verbose_name='SNMP用户名')),
                ('snmp_auth_password_encrypted', models.TextField(blank=True, help_text='SNMPv3使用，Fernet加密存储', verbose_name='认证密码（加密）')),
                ('snmp_priv_password_encrypted', models.TextField(blank=True, help_text='SNMPv3使用，Fernet加密存储', verbose_name='隐私密码（加密）')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用扫描')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='最后扫描时间')),
                ('last_scan_status', models.CharField(blank=True, help_text='success/failed/timeout', max_length=20, verbose_name='最后扫描状态')),
                ('last_scan_error', models.TextField(blank=True, verbose_name='最后扫描错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='ipam_networ_name_c90393_idx'), models.Index(fields=['ip_address'], name='ipam_networ_ip_addr_86c8ff_idx'), models.Index(fields=['enabled'], name='ipam_networ_enabled_4580b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP地址')),
                ('status', models.CharField(choices=[('available', '可用'), ('allocated', '已分配'), ('reserved', '保留'), ('conflict', '冲突')], db_index=True, default='available', max_length=20, verbose_name='状态')),
                ('hostname', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=17, validators=[ipam.models.MACAddressValidator()], verbose_name='MAC地址')),
                ('device_type', models.CharField(blank=True, help_text='例如: 服务器、打印机、工控机', max_length=100, verbose_name='设备类型')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='使用部门')),
                ('responsible_person', models.CharField(blank=True, max_length=100, verbose_name='责任人')),
                ('allocated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='分配时间')),
                ('conflict_detected_at', models.DateTimeField(blank=True, null=True, verbose_name='冲突检测时间')),
                ('previous_mac_address', models.CharField(blank=True, help_text='用于检测MAC地址变化', max_length=17, verbose_name='之前的MAC地址')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_ips', to=settings.AUTH_USER_MODEL, verbose_name='分配人')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='ipam.subnet', verbose_name='所属子网')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
                'ordering': ['address'],
                'indexes': [models.Index(fields=['address'], name='ipam_ipaddr_address_648a1f_idx'), models.Index(fields=['status'], name='ipam_ipaddr_status_b5df62_idx'), models.Index(fields=['subnet', 'status'], name='ipam_ipaddr_subnet__ffd89c_idx'), models.Index(fields=['mac_address'], name='ipam_ipaddr_mac_add_1f2ecb_idx'), models.Index(fields=['hostname'], name='ipam_ipaddr_hostnam_20c219_idx'), models.Index(fields=['allocated_at'], name='ipam_ipaddr_allocat_152b46_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间戳')),
                ('action', models.CharField(choices=[('allocate', '分配IP'), ('release', '释放IP'), ('update', '更新IP'), ('delete', '删除IP'), ('create_subnet', '创建子网'), ('update_subnet', '更新子网'), ('delete_subnet', '删除子网'), ('snmp_scan', 'SNMP扫描'), ('conflict_detected', '检测到冲突')], db_index=True, max_length=50, verbose_name='操作类型')),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45, verbose_name='IP地址')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC地址')),
                ('details', models.JSONField(blank=True, help_text='额外的操作详情，JSON格式', null=True, verbose_name='详细信息')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='ipam_auditl_timesta_3bd338_idx'), models.Index(fields=['action'], name='ipam_auditl_action_6e6645_idx'), models.Index(fields=['ip_address'], name='ipam_auditl_ip_addr_16ae81_idx'), models.Index(fields=['user', '-timestamp'], name='ipam_auditl_user_id_bb9431_idx')],
            },
        ),
    ]
