# Generated by Django 4.2.11 on 2026-01-04 06:10

from django.db import migrations, connection


def create_postgresql_triggers(apps, schema_editor):
    """仅在 PostgreSQL 数据库上创建触发器"""
    if connection.vendor != 'postgresql':
        return  # SQLite 不支持触发器

    with connection.cursor() as cursor:
        # 创建防止更新审计日志的触发器
        cursor.execute("""
            CREATE OR REPLACE FUNCTION prevent_audit_log_update()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Audit logs cannot be modified';
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
        """)

        cursor.execute("""
            DROP TRIGGER IF EXISTS audit_log_prevent_update ON ipam_auditlog;
            CREATE TRIGGER audit_log_prevent_update
            BEFORE UPDATE ON ipam_auditlog
            FOR EACH ROW
            EXECUTE FUNCTION prevent_audit_log_update();
        """)

        # 创建防止删除审计日志的触发器
        cursor.execute("""
            CREATE OR REPLACE FUNCTION prevent_audit_log_delete()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Audit logs cannot be deleted';
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
        """)

        cursor.execute("""
            DROP TRIGGER IF EXISTS audit_log_prevent_delete ON ipam_auditlog;
            CREATE TRIGGER audit_log_prevent_delete
            BEFORE DELETE ON ipam_auditlog
            FOR EACH ROW
            EXECUTE FUNCTION prevent_audit_log_delete();
        """)


def drop_postgresql_triggers(apps, schema_editor):
    """删除 PostgreSQL 触发器"""
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        cursor.execute("DROP TRIGGER IF EXISTS audit_log_prevent_update ON ipam_auditlog;")
        cursor.execute("DROP FUNCTION IF EXISTS prevent_audit_log_update();")
        cursor.execute("DROP TRIGGER IF EXISTS audit_log_prevent_delete ON ipam_auditlog;")
        cursor.execute("DROP FUNCTION IF EXISTS prevent_audit_log_delete();")


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_postgresql_triggers,
            reverse_code=drop_postgresql_triggers,
        ),
    ]
