# Generated by Django 4.2.11 on 2026-01-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        # 创建防止更新审计日志的触发器
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION prevent_audit_log_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    RAISE EXCEPTION 'Audit logs cannot be modified';
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER audit_log_prevent_update
                BEFORE UPDATE ON ipam_auditlog
                FOR EACH ROW
                EXECUTE FUNCTION prevent_audit_log_update();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS audit_log_prevent_update ON ipam_auditlog;
                DROP FUNCTION IF EXISTS prevent_audit_log_update();
            """
        ),

        # 创建防止删除审计日志的触发器
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION prevent_audit_log_delete()
                RETURNS TRIGGER AS $$
                BEGIN
                    RAISE EXCEPTION 'Audit logs cannot be deleted';
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER audit_log_prevent_delete
                BEFORE DELETE ON ipam_auditlog
                FOR EACH ROW
                EXECUTE FUNCTION prevent_audit_log_delete();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS audit_log_prevent_delete ON ipam_auditlog;
                DROP FUNCTION IF EXISTS prevent_audit_log_delete();
            """
        ),
    ]
