# Generated by Django 4.2.11 on 2026-01-04 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_add_audit_log_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='building',
            field=models.CharField(blank=True, db_index=True, help_text='例如: M1, M2, M3', max_length=10, verbose_name='楼栋'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='floor',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='楼层'),
        ),
    ]
