# Generated by Django 4.2.11 on 2026-01-05 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_add_building_floor_to_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ipam.subnet', verbose_name='关联子网'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='subnet_network',
            field=models.CharField(blank=True, help_text='冗余存储，防止子网删除后丢失信息', max_length=43, verbose_name='子网地址（快照）'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='device_type',
            field=models.CharField(blank=True, choices=[('server', '服务器'), ('workstation', '工作站'), ('printer', '打印机'), ('network', '网络设备'), ('clean_instrument', '洁净仪'), ('iot', '物联网设备'), ('camera', '监控摄像头'), ('access_control', '门禁设备'), ('plc', 'PLC控制器'), ('hmi', '触摸屏/HMI'), ('robot', '机器人'), ('agv', 'AGV小车'), ('scanner', '扫码枪'), ('sensor', '传感器'), ('other', '其他')], help_text='例如: 服务器、打印机、工控机', max_length=100, verbose_name='设备类型'),
        ),
    ]
