# Generated by Django 4.2.11 on 2026-01-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_ui_optimization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('occupied', '已占用'), ('allocated', '已分配'), ('reserved', '保留'), ('conflict', '冲突')], db_index=True, default='available', max_length=20, verbose_name='状态'),
        ),
    ]
