# Generated by Django 4.2.11 on 2026-01-05 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_add_occupied_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='building',
            field=models.CharField(blank=True, help_text='例如: M1, M2, M3', max_length=10, verbose_name='楼栋'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='floor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='楼层'),
        ),
    ]
