# Generated by Django 4.2.11 on 2026-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    添加 is_global 字段到 Subnet 模型

    数据完整性考虑：
    1. 使用安全的默认值 False
    2. NOT NULL 约束确保数据一致性
    3. 添加数据库索引提升查询性能
    4. 可安全回滚
    """

    dependencies = [
        ('ipam', '0006_add_building_floor_to_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnet',
            name='is_global',
            field=models.BooleanField(
                default=False,
                verbose_name='全局子网',
                help_text='标记为全局子网，所有用户可见可用',
                db_index=True,  # 添加索引用于高效过滤
            ),
        ),
    ]
