# Generated by Django 4.2.11 on 2026-01-05 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    添加 scan_interval_minutes 字段到 NetworkDevice 模型

    数据完整性考虑：
    1. 使用合理的默认值 30 分钟
    2. 添加验证器确保扫描间隔在合理范围（1-1440分钟，即1分钟到24小时）
    3. NOT NULL 约束防止空值
    4. 可安全回滚
    5. 对现有数据无影响，所有记录自动获得默认值
    """

    dependencies = [
        ('ipam', '0007_add_is_global_to_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='scan_interval_minutes',
            field=models.IntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(1, message='扫描间隔至少为1分钟'),
                    django.core.validators.MaxValueValidator(1440, message='扫描间隔最多为1440分钟(24小时)'),
                ],
                verbose_name='扫描间隔(分钟)',
                help_text='自动扫描的时间间隔，范围: 1-1440分钟',
            ),
        ),
    ]
