# Generated by Django 4.2.11 on 2026-01-05 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    添加连续缺失计数和最后发现时间字段到 IpAddress 模型

    数据完整性考虑：
    1. consecutive_missing: 默认值 0，使用 NOT NULL 确保数据一致性
    2. last_seen_at: 允许 NULL (blank=True, null=True)，因为新创建的IP可能还未被扫描
    3. 添加验证器防止 consecutive_missing 为负数
    4. 添加数据库索引提升查询性能（用于查找长期离线设备）
    5. 对现有数据安全：
       - 现有IP记录的 consecutive_missing 自动设置为 0（表示未检测到缺失）
       - 现有IP记录的 last_seen_at 为 NULL（表示扫描历史未知）
    6. 可安全回滚
    """

    dependencies = [
        ('ipam', '0008_add_scan_interval_to_networkdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='consecutive_missing',
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0, message='连续缺失次数不能为负数'),
                ],
                verbose_name='连续缺失次数',
                help_text='SNMP扫描中连续未发现该IP的次数',
                db_index=True,  # 索引用于查找长期离线设备
            ),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_seen_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='最后发现时间',
                help_text='SNMP扫描最后一次发现该IP在线的时间',
                db_index=True,  # 索引用于按时间排序查询
            ),
        ),
    ]
