# Generated by Django 4.2.11 on 2026-01-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0009_add_tracking_fields_to_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('switch', '交换机'), ('router', '路由器'), ('firewall', '防火墙'), ('wireless_controller', '无线控制器'), ('ap', '无线AP'), ('other', '其他')], default='switch', max_length=50, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('allocate', '分配IP'), ('release', '释放IP'), ('update', '更新IP'), ('delete', '删除IP'), ('create_subnet', '创建子网'), ('update_subnet', '更新子网'), ('delete_subnet', '删除子网'), ('snmp_scan', 'SNMP扫描'), ('scan', '网络扫描'), ('conflict_detected', '检测到冲突'), ('conflict_resolved', '冲突已解决'), ('device_discovered', '发现设备')], db_index=True, max_length=50, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='device_type',
            field=models.CharField(blank=True, choices=[('server', '服务器'), ('workstation', '工作站'), ('printer', '打印机'), ('network', '网络设备'), ('clean_instrument', '洁净仪'), ('iot', '物联网设备'), ('camera', '监控摄像头'), ('access_control', '门禁设备'), ('plc', 'PLC控制器'), ('hmi', '触摸屏/HMI'), ('robot', '机器人'), ('agv', 'AGV小车'), ('scanner', '扫码枪'), ('sensor', '传感器'), ('wireless_controller', '无线控制器'), ('other', '其他')], help_text='例如: 服务器、打印机、工控机', max_length=100, verbose_name='设备类型'),
        ),
    ]
