# Generated by Claude - Fix audit log trigger to allow SET_NULL on user deletion

from django.db import migrations


class Migration(migrations.Migration):
    """
    修复审计日志触发器，允许用户删除时的 SET_NULL 操作。

    问题：原触发器阻止所有 UPDATE 操作，导致删除用户时因
    Django 的 on_delete=SET_NULL 触发 UPDATE 而失败。

    解决方案：允许仅将 user_id 从非空设为 NULL 的操作，
    同时确保其他字段未被修改。
    """

    dependencies = [
        ('ipam', '0010_add_network_device_type_description'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE OR REPLACE FUNCTION prevent_audit_log_update()
            RETURNS TRIGGER AS $$
            BEGIN
                -- 允许的情况：仅将 user_id 从非空设为 NULL（用户删除触发的 SET_NULL）
                IF OLD.user_id IS NOT NULL AND NEW.user_id IS NULL THEN
                    -- 检查其他字段是否被修改（使用 IS NOT DISTINCT FROM 处理 NULL 值）
                    IF OLD.timestamp = NEW.timestamp
                       AND OLD.action = NEW.action
                       AND OLD.ip_address IS NOT DISTINCT FROM NEW.ip_address
                       AND OLD.hostname IS NOT DISTINCT FROM NEW.hostname
                       AND OLD.mac_address IS NOT DISTINCT FROM NEW.mac_address
                       AND OLD.subnet_id IS NOT DISTINCT FROM NEW.subnet_id
                       AND OLD.subnet_network IS NOT DISTINCT FROM NEW.subnet_network
                       AND OLD.details::text IS NOT DISTINCT FROM NEW.details::text
                    THEN
                        -- 仅 user_id 被设为 NULL，允许此操作
                        RETURN NEW;
                    END IF;
                END IF;

                -- 其他任何修改都拒绝
                RAISE EXCEPTION 'Audit logs cannot be modified';
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
            ''',
            reverse_sql='''
            CREATE OR REPLACE FUNCTION prevent_audit_log_update()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Audit logs cannot be modified';
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
            '''
        ),
    ]
